recepients:
  - name: "Islam"
    email: "islam.asous1@gmail.com"
    phone: +19178378908

  - name: "Maida"
    email: "maidakuc5@gmail.com"
    phone: +19178863883

  - name: "Enzo"
    email: "vincenzomonterosso9@gmail.com"
    phone: +19178081673

  - name: "Alejandro"
    email: "moyaramirez2003@gmail.com"
    phone: +19144862399